version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_PROPAGATORS=tracecontext,baggage
    depends_on:
      - otel-collector
      - fluent-bit
    networks:
      - observability
    


  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector/config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    networks:
      - observability

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"   # Jaeger UI
      - "14250:14250"   # gRPC ingest from collector
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090" # Prometheus UI
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alert_rules.yaml:/etc/prometheus/alert_rules.yaml
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--enable-feature=exemplar-storage"
    networks:
      - observability

  loki:
    image: grafana/loki:latest    
    ports:
      - "3100:3100" # API / ingestion
    networks:
      - observability

  fluent-bit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./config/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./config/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    networks:
      - observability
  
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./config/alert-manager/alertmanager.yaml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"  # Grafana web UI
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./config/grafana/dashboards.json:/etc/grafana/provisioning/dashboards/dashboard.json
    depends_on:
      - prometheus
      - loki
      - jaeger
    networks:
      - observability
    
  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6/load-test.js:/load-test.js
    command: run /load-test.js
    profiles:
      - tools
    depends_on:
      - app
    networks:
      - observability


networks:
  observability:
    driver: bridge